"""MySQL users table + salted hashing (no chat storage)."""
import os
import hashlib
import secrets
from typing import Optional, Tuple
import pymysql
from dotenv import load_dotenv

# Load environment variables
load_dotenv()


class UserDB:
    """Handles MySQL connection and user credential management."""
    
    def __init__(self, auto_connect: bool = True):
        """Initialize database connection from environment variables."""
        self.host = os.getenv("DB_HOST", "localhost")
        self.user = os.getenv("DB_USER", "root")
        self.password = os.getenv("DB_PASSWORD")
        self.database = os.getenv("DB_NAME", "securechat")
        self.connection = None
        
        # Automatically connect if requested
        if auto_connect:
            self.connect()
    
    def connect(self) -> None:
        """Establish connection to MySQL database."""
        try:
            self.connection = pymysql.connect(
                host=self.host,
                user=self.user,
                password=self.password,
                database=self.database,
                charset='utf8mb4',
                cursorclass=pymysql.cursors.DictCursor
            )
        except pymysql.Error as e:
            raise RuntimeError(f"Failed to connect to MySQL: {e}")
    
    def disconnect(self) -> None:
        """Close database connection."""
        if self.connection:
            self.connection.close()
            self.connection = None
    
    def __enter__(self):
        """Context manager entry - establish connection."""
        self.connect()
        return self
    
    def __exit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit - close connection."""
        self.disconnect()
    
    @staticmethod
    def generate_salt() -> bytes:
        """Generate a cryptographically secure 16-byte random salt."""
        return secrets.token_bytes(16)
    
    @staticmethod
    def hash_password(password: str, salt: bytes) -> str:
        """
        Compute salted SHA-256 hash of password.
        
        Args:
            password: plaintext password
            salt: 16-byte random salt
            
        Returns:
            Hex-encoded SHA-256 hash of (salt || password)
        """
        # Concatenate salt and password, then hash
        combined = salt + password.encode('utf-8')
        pwd_hash = hashlib.sha256(combined).hexdigest()
        return pwd_hash
    
    def register_user(self, email: str, username: str, password: str) -> Tuple[bool, str]:
        """
        Register a new user with salted password hash.
        
        Args:
            email: user email address
            username: unique username
            password: plaintext password (will be hashed)
            
        Returns:
            Tuple of (success: bool, message: str)
            - (True, "Registration successful") if user created
            - (False, "User already exists") if email/username taken
            
        Raises:
            RuntimeError: if database operation fails
        """
        if not self.connection:
            raise RuntimeError("Not connected to database")
        
        # Generate random salt
        salt = self.generate_salt()
        
        # Compute salted hash
        pwd_hash = self.hash_password(password, salt)
        
        try:
            with self.connection.cursor() as cursor:
                # Check if user already exists
                cursor.execute(
                    "SELECT id FROM users WHERE email = %s OR username = %s",
                    (email, username)
                )
                if cursor.fetchone():
                    return False, "User already exists"  # User already exists
                
                # Insert new user
                cursor.execute(
                    """
                    INSERT INTO users (email, username, salt, pwd_hash)
                    VALUES (%s, %s, %s, %s)
                    """,
                    (email, username, salt, pwd_hash)
                )
                self.connection.commit()
                return True, "Registration successful"
        except pymysql.Error as e:
            self.connection.rollback()
            raise RuntimeError(f"Failed to register user: {e}")
    
    def register_user_with_hash(self, email: str, username: str, salt: bytes, pwd_hash_b64: str) -> Tuple[bool, str]:
        """
        Register a new user with pre-computed salt and password hash (from client).
        
        This method accepts the salt and hashed password directly from the client,
        per assignment protocol where client does: pwd_hash = SHA256(salt || password)
        
        Args:
            email: user email address
            username: unique username
            salt: 16-byte salt (already generated by client)
            pwd_hash_b64: base64-encoded SHA256(salt||password) from client
            
        Returns:
            Tuple of (success: bool, message: str)
            - (True, "Registration successful") if user created
            - (False, "User already exists") if email/username taken
        """
        if not self.connection:
            raise RuntimeError("Not connected to database")
        
        import base64
        # Convert base64 pwd_hash to hex for storage (64 hex chars = 32 bytes = SHA-256)
        pwd_hash_bytes = base64.b64decode(pwd_hash_b64)
        pwd_hash_hex = pwd_hash_bytes.hex()
        
        try:
            with self.connection.cursor() as cursor:
                # Check if user already exists
                cursor.execute(
                    "SELECT id FROM users WHERE email = %s OR username = %s",
                    (email, username)
                )
                if cursor.fetchone():
                    return False, "User already exists"
                
                # Insert new user with client-provided salt and hash
                cursor.execute(
                    """
                    INSERT INTO users (email, username, salt, pwd_hash)
                    VALUES (%s, %s, %s, %s)
                    """,
                    (email, username, salt, pwd_hash_hex)
                )
                self.connection.commit()
                return True, "Registration successful"
        except pymysql.Error as e:
            self.connection.rollback()
            raise RuntimeError(f"Failed to register user: {e}")
    
    def get_user_salt(self, email: str) -> Optional[bytes]:
        """
        Get user's salt for login password hashing.
        
        Client needs the salt to compute: pwd_hash = SHA256(salt || password)
        before sending login credentials.
        
        Args:
            email: user email address
            
        Returns:
            16-byte salt if user exists, None otherwise
        """
        if not self.connection:
            raise RuntimeError("Not connected to database")
        
        try:
            with self.connection.cursor() as cursor:
                cursor.execute(
                    "SELECT salt FROM users WHERE email = %s",
                    (email,)
                )
                result = cursor.fetchone()
                return result['salt'] if result else None
        except pymysql.Error as e:
            raise RuntimeError(f"Failed to get salt: {e}")
    
    def verify_login_with_hash(self, email: str, pwd_hash_b64: str) -> Tuple[bool, Optional[str]]:
        """
        Verify user credentials with pre-hashed password from client.
        
        Client sends: pwd_hash = SHA256(salt || password)
        Server compares this with stored hash directly (no re-hashing needed).
        
        Args:
            email: user email address
            pwd_hash_b64: base64-encoded SHA256(salt||password) from client
            
        Returns:
            Tuple of (success: bool, username_or_error: Optional[str])
            - (True, username) if credentials valid
            - (False, error_message) if credentials invalid or user not found
        """
        if not self.connection:
            raise RuntimeError("Not connected to database")
        
        import base64
        # Convert base64 to hex for comparison
        pwd_hash_bytes = base64.b64decode(pwd_hash_b64)
        pwd_hash_hex = pwd_hash_bytes.hex()
        
        try:
            with self.connection.cursor() as cursor:
                # Fetch user record
                cursor.execute(
                    "SELECT username, pwd_hash FROM users WHERE email = %s",
                    (email,)
                )
                result = cursor.fetchone()
                
                if not result:
                    return False, "User not found"
                
                username = result['username']
                stored_hash = result['pwd_hash']
                
                # Constant-time comparison
                if secrets.compare_digest(pwd_hash_hex, stored_hash):
                    return True, username
                else:
                    return False, "Invalid password"
        except pymysql.Error as e:
            raise RuntimeError(f"Failed to verify login: {e}")
    
    def verify_login(self, email: str, password: str) -> Tuple[bool, Optional[str]]:
        """
        Verify user credentials during login.
        
        Args:
            email: user email address
            password: plaintext password to verify
            
        Returns:
            Tuple of (success: bool, username_or_error: Optional[str])
            - (True, username) if credentials valid
            - (False, error_message) if credentials invalid or user not found
            
        Raises:
            RuntimeError: if database operation fails
        """
        if not self.connection:
            raise RuntimeError("Not connected to database")
        
        try:
            with self.connection.cursor() as cursor:
                # Fetch user record
                cursor.execute(
                    "SELECT username, salt, pwd_hash FROM users WHERE email = %s",
                    (email,)
                )
                result = cursor.fetchone()
                
                if not result:
                    return False, "User not found"  # User not found
                
                username = result['username']
                salt = result['salt']
                stored_hash = result['pwd_hash']
                
                # Recompute hash with provided password
                computed_hash = self.hash_password(password, salt)
                
                # Constant-time comparison to prevent timing attacks
                if secrets.compare_digest(computed_hash, stored_hash):
                    return True, username
                else:
                    return False, "Invalid password"
        except pymysql.Error as e:
            raise RuntimeError(f"Failed to verify login: {e}")
    
    def user_exists(self, email: str) -> bool:
        """
        Check if a user with given email exists.
        
        Args:
            email: user email address
            
        Returns:
            True if user exists, False otherwise
        """
        if not self.connection:
            raise RuntimeError("Not connected to database")
        
        try:
            with self.connection.cursor() as cursor:
                cursor.execute("SELECT id FROM users WHERE email = %s", (email,))
                return cursor.fetchone() is not None
        except pymysql.Error as e:
            raise RuntimeError(f"Failed to check user existence: {e}")


def main():
    """Test database operations (for development/testing only)."""
    print("Testing SecureChat Database Layer")
    print("-" * 50)
    
    try:
        with UserDB() as db:
            print("✓ Connected to MySQL database")
            
            # Test registration
            test_email = "test@example.com"
            test_username = "testuser"
            test_password = "TestPass123!"
            
            print(f"\nTesting registration for {test_email}...")
            success = db.register_user(test_email, test_username, test_password)
            if success:
                print("✓ User registered successfully")
            else:
                print("⚠ User already exists")
            
            # Test login with correct password
            print(f"\nTesting login with correct password...")
            success, username = db.verify_login(test_email, test_password)
            if success:
                print(f"✓ Login successful, username: {username}")
            else:
                print("✗ Login failed")
            
            # Test login with wrong password
            print(f"\nTesting login with wrong password...")
            success, username = db.verify_login(test_email, "WrongPassword")
            if not success:
                print("✓ Login correctly rejected")
            else:
                print("✗ Security issue: accepted wrong password!")
            
            print("\n" + "-" * 50)
            print("Database layer tests completed")
    
    except Exception as e:
        print(f"✗ Error: {e}")


if __name__ == "__main__":
    main()
